name: build nodejs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - nodejs/**
jobs:
  push:
    name: "images:nodejs_${{ matrix.tag }}"
    runs-on: ubuntu-latest
      
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 16
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
         
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      - name: Login to GitHub Package Registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/wmade/images:nodejs_${{ matrix.tag }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./nodejs
          file: ./nodejs/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/wmade/images:nodejs_${{ matrix.tag }}
